name: Test OnlyAccept
description: diagnostic
title: '[TestOnlyAccept] '
body:
- type: upload
  id: asset_upload
  attributes:
    label: App Assets
  validations:
    required: true
    accept: .pkg,.zip,.png,.jpg,.jpeg
